name: sdm_handal
version: 2.0.1+2
publish_to: none
description: Aplikasi kepegawaian RS Bhayangkara Nganjuk.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  animated_splash_screen: ^1.1.0
  animations: ^2.0.1
  cached_network_image: ^3.1.0
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.1
  fl_chart: 0.36.1
  flutter_colorpicker: ^0.4.0
  flutter_datetime_picker: ^1.5.1
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_reaction_button: ^1.0.8
  flutter_svg: ^0.22.0
  flutter_vector_icons: ^1.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  location: ^4.3.0
  map_launcher: ^2.1.1
  nb_utils: 4.4.10
  otp_text_field: ^1.1.1
  outlined_text: ^1.0.1
  photo_view: ^0.14.0
  search_choices: ^2.0.14
  signature: ^4.1.1
  simple_animations: ^3.1.1
  smart_select: 4.2.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.6
  lottie: ^1.2.1
  calendar_timeline: 1.0.4
  getwidget: 2.0.4
  device_info_plus: ^4.0.0
  onesignal_flutter: 3.2.8
  syncfusion_flutter_charts: ^20.1.59
  responsive_grid: ^2.1.0
  syncfusion_flutter_signaturepad: ^20.1.56
  geolocator: ^9.0.0
  package_info: 2.0.2
  pdfx: ^2.3.0
  internet_file: ^1.2.0
  mobile_scanner: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: images/walletApp/logo_rsbnganjuk.png
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - fonts/
    - assets/
    - assets/ca/
    - assets/pdf/
    - images/
    - images/widgets/
    - images/walletApp/
    - images/lottie/
  fonts: 
    - family: Andina
      fonts: 
        - asset: fonts/andina.ttf
    - family: Regular
      fonts: 
        - asset: fonts/googlesansregular.ttf
    - family: Medium
      fonts: 
        - asset: fonts/googlesansmedium.ttf
    - family: Semibold
      fonts: 
        - asset: fonts/googlesansmedium.ttf
    - family: Bold
      fonts: 
        - asset: fonts/googlesansebold.ttf
  uses-material-design: true

