name: sdm_handal
description: Aplikasi kepegawaian RS Bhayangkara Nganjuk.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_splash_screen: ^1.1.0
  animations: ^2.0.1
  cached_network_image: ^3.1.0
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.1
  fl_chart: 0.36.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.4.0
  flutter_datetime_picker: ^1.5.1
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_reaction_button: ^1.0.8
  flutter_svg: ^0.22.0
  flutter_vector_icons: ^1.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  location: ^4.3.0
  map_launcher: ^2.1.1
  nb_utils: ^4.4.8
  otp_text_field: ^1.1.1
  outlined_text: ^1.0.1
  photo_view: ^0.12.0
  search_choices: ^2.0.14
  signature: ^4.1.1
  simple_animations: ^3.1.1
  smart_select: ^4.3.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.12
  lottie: ^1.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/walletApp/logo_rsbnganjuk.png"

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - fonts/
    - assets/
    - images/
    - images/widgets/
    - images/walletApp/
    - images/lottie/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf
